DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS record;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE event (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  eventname TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL,
  hornored TEXT,
  comments TEXT,
);

CREATE user_event (
  user_id INTEGER,
  event_id INTEGER,
  role INTEGER,
  PRIMARY KEY (user_id, event_id),
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (event_id) REFERENCES event (id)
);

CREATE TABLE record (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  guestseq INTEGER NOT NULL,
  guestname TEXT NOT NULL,
  guestcount INTGER NOT NULL DEFAULT 1,
  registertime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (scannednode) REFERENCES user (id),
  FOREIGN KEY (evnentid) REFERENCES event (id)
)
